
export const data = [


  {
    id: 1,
    date: " Today, 1:00 . 2nd ODI . Visakhaptnam ",
    image: 'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/340400/340493.png',
    images:'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/313100/313128.logo.png',
   name:'India',
   names:' Australia',
   match:'Match starts in 1hr',
   btn:'Schedule',
   btn1:'Videos',
   btn2:'Series',
  },
  {
    id: 2,
    date: " Today, 1:00 . 2nd ODI . Visakhaptnam ",
    image: 'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/355900/355991.png',
    images:'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/355900/355992.png',
   name:'Spain',
   names:' Europe',
   match:'Match starts in 1hr',
   btn:'Schedule',
   btn1:'Videos',
 
  },
  {
    id: 3,
    date: " Today, 1:00 . 2nd ODI . Visakhaptnam ",
    image: 'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/355500/355583.png',
    images:'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/355600/355624.png',
   name:'Afghanistan',
   names:' Kabul',
   match:'Kabul need 134 runs from 15.3 overs.',
   btn:'Schedule',
   btn1:'Videos',
   btn2:'Series',
   btn3:'Tables',
  },
  {
    id: 4,
    date: " Today, 1:00 . 2nd ODI . Visakhaptnam ",
    image: 'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/341400/341456.png',
    images:'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/313100/313149.logo.png',
   name:'BanglaDesh',
   names:' Newziland',
   match:'New Zealand won by an innings and 58 runs',
   btn:'Schedule',
   btn1:'Videos',
   btn2:'Series',
  },

  {
    id: 5,
    date: " Today, 1:00 . 2nd ODI . Visakhaptnam ",
    image: 'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/340400/340493.png',
    images:'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/313100/313128.logo.png',
   name:'India',
   names:' Australia',
   match:'Match starts in 1hr',
   btn:'Schedule',
   btn1:'Videos',
   btn2:'Series',
  },
  {
    id: 6,
    date: " Today, 1:00 . 2nd ODI . Visakhaptnam ",
    image: 'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/355900/355991.png',
    images:'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/355900/355992.png',
   name:'Spain',
   names:' Europe',
   match:'Match starts in 1hr',
   btn:'Schedule',
   btn1:'Videos',
   btn2:'Series',
   btn3:'Tables',
  },
  {
    id: 7,
    date: " Today, 1:00 . 2nd ODI . Visakhaptnam ",
    image: 'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/355500/355583.png',
    images:'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/355600/355624.png',
   name:'Afghanistan',
   names:' Kabul',
   match:'Kabul need 134 runs from 15.3 overs.',
   btn:'Schedule',
   btn1:'Videos',
   btn2:'Series',
  },
  {
    id: 8,
    date: " Today, 1:00 . 2nd ODI . Visakhaptnam ",
    image: 'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/341400/341456.png',
    images:'https://img1.hscicdn.com/image/upload/f_auto,t_ds_square_w_80/lsci/db/PICTURES/CMS/313100/313149.logo.png',
   name:'BanglaDesh',
   names:' Newziland',
   match:'New Zealand won by an innings and 58 runs',
   btn:'Schedule',
   btn1:'Videos',
   btn2:'Series',
  },
  



];